name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . -t docker_image
    - name: Create new container from image
      run: docker container create --name ariana docker_image 
    - name: Start the container from the built image
      run: docker start ariana
    - name: Copy log file from container to the host machine
      run: docker cp ariana:/var/log/dfcti_system_logs.log /var/log/
    - uses: actions/upload-artifact@v2
      with:
        name: plots
        path: /var/log/dfcti_system_logs.log
        if-no-files-found: error
