name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . -t dockerbuild
    - name: Run the built image
      run: docker run dockerbuild
    - uses: actions/upload-artifact@v2
      with:
        name: plots
        path: /var/log/dfcti*.log
