on:
  workflow_run:
    workflows: [ "Build-Applications" ]
    types:
      - completed

jobs:

  create-release:
    name: Release apps
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test docker
      run: |
        docker images
        docker ps -a