name: Release-Applications

on:
  workflow_run:
    workflows: [ "Build-Applications" ]
    types:
      - completed

jobs:

  create-release:
    name: Release apps
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ahmadnassri/action-workflow-run-wait@v1
    - name: Create release with artifact
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        title: "Apps"
        files: |
          Dockerfile